### PR TITLE
Adds Page.add_cookies/2 and Page.cookies/1

### PR DESCRIPTION
**Pull request by dbrody**
Adds basic functional to add and get cookies on a page.

```elixir

# Add Cookies
page |> Playwright.Page.add_cookies([%{...cookie...}])

# Get Cookies
cookies = page |> Playwright.Page.cookies()

```

### CODE REVIEW

**Comment by coreyti** [comment]
Hey @dbrody, 

I'm delighted to see you contributing PRs... thanks!

Overall, this looks good. We do have some challenges to figure out before pulling in the change related to the management of, and testing against, test assets:

1. The embedded `assets_server/assets` are actually pulled, as a git sub-tree, from the canonical [playwright](https://github.com/microsoft/playwright) repository, rather than being "manually" copied. What this means is that the `cookiesapi.html` file you added would be conflicting or removed when that assets folder is updated with upstream changes. I'm not sure how best to solve this. One possible solution would be to have a sibling folder to `assets` for "local" assets, and update the `AssetsServer.Router` to serve a second path. Thoughts?
2. At the moment, there is a *separate* (and duplicate, in some regard) [playwright-assets](https://github.com/geometerio/playwright-assets) project that takes a similar approach of bundling the assets as a git sub-tree and implements an external server to provide those assets. An intention is for that to become, in addition to being a standalone server, an Elixir package that could be used as a dependency for this project, replacing the embedded assets. For the time being, it is used as the assets server in the CI pipeline for this project. The downside to this is, any fix we make to the embedded assets approach would need to be duplicate to `playwright-assets` in order for CI to pass. I'm not entirely sure how best to solve this either. @woodward and I did some exploration yesterday toward a solution for making `playwright-assets` capable as an Elixir package. That is likely the be the best approach. Another might be to try to switch this pipeline to use the `:driver` transport instead of `:websocket` transport and see if the embedded assets server does the job (I don't recall if I set it up with the WS approach because of some problem, or just for the coverage).

I'll think on this some, and am happy to hear thoughts/suggestions/concerns.

**Comment by dbrody** [comment]
Got it. Whatever you think is best. I'm not sure the rationale behind separating the two packages but I'm more than happy to just add the file to the playwright-assets repo. It seems like making option 2 functional asap is a good idea then.

**Comment by coreyti** [comment]
I'll find some time today to get the `playwright-assets` project working as an Elixir dep, and then we can add your `cookiesapi.html` asset there (I'm thinking along the lines of adding an "extras" path, sibling to the assets from the main playwright repo).

**Comment by coreyti** [comment]
Hi @dbrody,

I decided to update the local, embedded assets server for now. I've added an "/extras" route to the server to provide assets from a, well, "extras" folder that is sibling to the "assets" folder. A usage example can be found in [assets_server_test.exs](https://github.com/geometerio/playwright-elixir/blob/b156df47a18b2ba4a4fa9480c35c5f8c7a2ee394/test/support/assets_server_test.exs).

This should unblock contributions like yours in this PR while maintaining the ability to pull in new assets from the ms/playwright, without waiting on the other work to package up playwright-assets.

Would you mind rebasing/rebuilding your PR based on that change?

**Comment by dbrody** [comment]
@coreyti Sounds good.

**Comment by dbrody** [comment]
@coreyti Let me know if the updates look ok. Thanks!

**Comment by coreyti** [comment]
Looks good, @dbrody. Merged. Thanks again for the PR!

**Comment by coreyti** [comment]
Hey @dbrody,

A heads-up: I recently moved this functionality from `Page` to `BrowserContext`. The change is more in-line with the API from the official Playwright projects, but is likely breaking for your usage. Apologies for any headaches caused.

**Comment by dbrody** [comment]
No problem, I understand this repo is under development and subject to change.
Happy to see it coming together.

**Pull request merged**
