### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by coreyti** [comment]
Hi @kianmeng,

Thanks for providing this PR. If you don't mind, please update the change to **exclude** any changes from the `priv/static` path. While it's true that you caught some spelling issues there, those files are generated from the official Playwright node.js repo, and it wouldn't make sense to fix the spelling here.

I'm definitely happy to have your contributions. Thanks!

**Comment by kianmeng** [comment]
@coreyti Sure. Please check.

**Comment by coreyti** [comment]
Looks good, @kianmeng; merged. Thanks for your contribution!

**Comment by kianmeng** [comment]
:tada: :tada: :tada: :tada: :tada:

**Pull request merged**
